version: '3'
services:
  db:
    image: postgres
    container_name: mirrorbrain-db
    volumes:
      - "/data/db:/var/lib/postgresql/data"
  web:
    image: kiwix/mirrorbrain
    container_name: mirrorbrain-web
    volumes:
      - "/data/download:/var/www/download.kiwix.org"
    ports:
      - 82:82
    links:
      - db
