version: '3'
services:
  db:
    image: postgres
    volumes:
      - "db-data:/var/lib/postgresql/data"
  web:
    image: kiwix/mirrorbrain
    volumes:
      - "/data/download:/var/www/download.kiwix.org"
    links:
      - db
volumes:
    db-data: 
