version: '3'
services:

  db:
    image: mysql:5
    container_name: matomo_mysql
    volumes:
      - "/data/matomo/mysql/conf:/etc/mysql/conf.d"
      - "/data/matomo/mysql/files:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root      
    restart: always

  app:
    image: matomo:fpm
    container_name: matomo_app
    volumes:
      - "appdir:/var/www/html"
    links:
      - db
    restart: always
    
  web:
    image: nginx:latest
    container_name: matomo_web
    volumes:
      - "appdir:/var/www/html"
      - "/data/matomo/web/conf:/etc/nginx/conf.d"
    links:
      - app
    environment:
      - VIRTUAL_HOST=stats.kiwix.org
      - LETSENCRYPT_HOST=stats.kiwix.org
      - LETSENCRYPT_EMAIL=contact@kiwix.org
      - HTTPS_METHOD=redirect
    networks:
      default:
        aliases:
          - stats
    restart: always
    
volumes:
  appdir:

networks:
  default:
    external:
      name: kiwix.org
