name: BitTorrent Tracker

on:
  push:
    branches:
      - 'main'
    paths:
      - 'bittorrent-tracker/**'

jobs:

  bittorrent-tracker:
    name: Deploy BitTorrent Tracker Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: kiwix/bittorrent-tracker
          on-master: latest
          restrict-to: kiwix/container-images
          context: bittorrent-tracker
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}