name: Docker

on:
  push:
    branches:
      - 'master'

jobs:
  dropbox:
    name: Deploy Dropbox Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Dropbox Docker Image
        uses: openzim/docker-publish-action@v8
        with:
          image-name: kiwix/dropbox
          on-master: latest
          restrict-to: kiwix/container-images
          context: dropbox
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  library:
    name: Deploy Library Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v6
        with:
          image-name: kiwix/library
          on-master: latest
          restrict-to: kiwix/container-images
          context: library
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  mirrorbrain:
    name: Deploy mirrorbrain Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v6
        with:
          image-name: kiwix/mirrorbrain
          on-master: latest
          restrict-to: kiwix/container-images
          context: mirrorbrain
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  rsyncd:
    name: Deploy rsyncd Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v6
        with:
          image-name: kiwix/rsyncd
          on-master: latest
          restrict-to: kiwix/container-images
          context: rsyncd
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  matomo:
    name: Deploy matomo Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v6
        with:
          image-name: kiwix/matomo
          on-master: latest
          restrict-to: kiwix/container-images
          context: matomo-server
          dockerfile: Dockerfile-app
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  matomologs:
    name: Deploy matomo logs Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v6
        with:
          image-name: kiwix/matomo-log-analytics
          on-master: latest
          restrict-to: kiwix/container-images
          context: matomo-log-analytics
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  surfer:
    name: Deploy Surfer Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v6
        with:
          image-name: openzim/surfer
          on-master: latest
          restrict-to: kiwix/container-images
          context: surfer
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

  bittorrent-tracker:
    name: Deploy BitTorrent Tracker Image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v6
        with:
          image-name: kiwix/bittorrent-tracker
          on-master: latest
          restrict-to: kiwix/container-images
          context: bittorrent-tracker
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
