name: Maintenance

on:
  push:
    branches:
      - 'main'
    paths:
      - 'maintenance/**'

jobs:

  maintenance:
    name: Deploy Maintenance Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: kiwix/maintenance
          on-master: latest
          restrict-to: kiwix/container-images
          context: maintenance
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}