name: Surfer

on:
  push:
    branches:
      - 'main'
    paths:
      - 'surfer/**'

jobs:

  surfer:
    name: Deploy Surfer Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/surfer
          on-master: latest
          restrict-to: kiwix/container-images
          context: surfer
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
